import type { UserRole } from "@shared/schema";

export function getDefaultRouteForRole(role: UserRole): string {
  const routeMap: Record<UserRole, string> = {
    administrator: "/users",
    training_officer: "/courses",
    manager: "/kpi-dashboard",
    foreman: "/approvals",
    employee: "/dashboard",
  };
  return routeMap[role] || "/dashboard";
}

export function isRouteAllowedForRole(role: UserRole, path: string): boolean {
  const allowedRoutes: Record<UserRole, string[]> = {
    employee: [
      "/",
      "/dashboard",
      "/my-courses",
      "/my-renewals",
      "/progression",
      "/recommendations",
      "/grade-readiness",
      "/kpi-dashboard",
      "/profile",
      "/settings",
    ],
    foreman: [
      "/",
      "/dashboard",
      "/my-courses",
      "/my-renewals",
      "/progression",
      "/recommendations",
      "/grade-readiness",
      "/kpi-dashboard",
      "/approvals",
      "/team",
      "/reports",
      "/profile",
      "/settings",
    ],
    manager: [
      "/",
      "/dashboard",
      "/my-courses",
      "/my-renewals",
      "/progression",
      "/recommendations",
      "/grade-readiness",
      "/kpi-dashboard",
      "/approvals",
      "/team",
      "/all-renewals",
      "/reports",
      "/profile",
      "/settings",
    ],
    training_officer: [
      "/",
      "/dashboard",
      "/courses",
      "/enrollments",
      "/all-renewals",
      "/reports",
      "/kpi-dashboard",
      "/profile",
      "/settings",
    ],
    administrator: [
      "/",
      "/dashboard",
      "/my-courses",
      "/my-renewals",
      "/progression",
      "/recommendations",
      "/grade-readiness",
      "/kpi-dashboard",
      "/approvals",
      "/team",
      "/courses",
      "/enrollments",
      "/all-renewals",
      "/users",
      "/departments",
      "/audit-logs",
      "/integrations",
      "/reports",
      "/profile",
      "/settings",
    ],
  };

  const routes = allowedRoutes[role] || [];
  return routes.includes(path);
}

export const roleToAllowedRoutes: Record<UserRole, string[]> = {
  employee: [
    "/",
    "/dashboard",
    "/my-courses",
    "/my-renewals",
    "/progression",
    "/recommendations",
    "/grade-readiness",
    "/kpi-dashboard",
    "/profile",
    "/settings",
  ],
  foreman: [
    "/",
    "/dashboard",
    "/my-courses",
    "/my-renewals",
    "/progression",
    "/recommendations",
    "/grade-readiness",
    "/kpi-dashboard",
    "/approvals",
    "/team",
    "/reports",
    "/profile",
    "/settings",
  ],
  manager: [
    "/",
    "/dashboard",
    "/my-courses",
    "/my-renewals",
    "/progression",
    "/recommendations",
    "/grade-readiness",
    "/kpi-dashboard",
    "/approvals",
    "/team",
    "/all-renewals",
    "/reports",
    "/profile",
    "/settings",
  ],
  training_officer: [
    "/",
    "/dashboard",
    "/courses",
    "/enrollments",
    "/all-renewals",
    "/reports",
    "/kpi-dashboard",
    "/profile",
    "/settings",
  ],
  administrator: [
    "/",
    "/dashboard",
    "/my-courses",
    "/my-renewals",
    "/progression",
    "/recommendations",
    "/grade-readiness",
    "/kpi-dashboard",
    "/approvals",
    "/team",
    "/courses",
    "/enrollments",
    "/all-renewals",
    "/users",
    "/departments",
    "/audit-logs",
    "/integrations",
    "/reports",
    "/profile",
    "/settings",
  ],
};
